#!/usr/bin/with-contenv sh

source /etc/postgresql/common.sh

if test -f $DB_ONETIME_COMPLETE; then
  exit
fi

if test -d $DB_PATH -a $DB_PATH/PG_VERSION; then
  echo "$WHOAMI $DB_PATH contains what appears to be a database"
  exit
fi

su postgres -c "initdb --auth=trust --pgdata \"$DB_PATH\""
if [ $? -ne 0 ]; then
  echo "$WHOAMI error initializing $DB_PATH" >&2
  exit 1
fi

# run setup in the background so it can wait for database cluster to start
$DB_SETUP_SH &
