#!/usr/bin/with-contenv sh

source /etc/postgresql/common.sh

if test -f $DB_ONETIME_COMPLETE; then
  exit
fi

if ! test -d $DB_PATH -a $DB_PATH/postgresql.conf; then
  echo "$WHOAMI no configuration file" >&2
  exit 1
fi

if [ -n "$DB_MAX_PREPARED_TRANSACTIONS" ]; then
  DB_MAX_CONNECTIONS=$DB_MAX_PREPARED_TRANSACTIONS
fi

if [ -n "$DB_MAX_CONNECTIONS" ]; then
  echo "$WHOAMI setting max_connections=$DB_MAX_CONNECTIONS"
  su postgres -c "sed -i -E -e 's/^max_connections *= *[0-9]+/max_connections=$DB_MAX_CONNECTIONS/' $DB_PATH/postgresql.conf"
fi

if [ -n "$DB_MAX_PREPARED_TRANSACTIONS" ]; then
  echo "$WHOAMI setting max_prepared_transactions=$DB_MAX_PREPARED_TRANSACTIONS"
  su postgres -c "sed -i -E -e 's/^#max_prepared_transactions *= *[0-9]+/max_prepared_transactions = $DB_MAX_PREPARED_TRANSACTIONS/' $DB_PATH/postgresql.conf"
fi
